classdef RDATFile
    properties
        version
        name
        sequence
	sequences
        structure
	structures
        offset
        seqpos
        annotations
        comments
        data_annotations
	reactivity
        reactivity_error
        xsel
        xsel_refine
        trace
    end
end
